version: 2
jobs:
  sendinfo:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/fadlyas07/kernel_dockerfile/master/gcc.sh
      - run: bash gcc.sh
